# Windows 7 and 10 build
build: false

before_build:
  - appveyor DownloadFile "https://drive.google.com/uc?export=download&id=1VTs8qaSiVAGO1BQYUbfafAXigDuxra5H" -FileName llvm-5.0.0.7z
  - 7z x llvm-5.0.0.7z -oC:\
  - set PATH=C:\llvm-5.0.0\bin;%PATH%
  - llvm-config --version

environment:
  #LLVM6: C:\Program Files\LLVM\bin
  #LLVM_CONFIG: C:\Program Files\LLVM\bin\llvm-config
  #PATH: "%LLVM6%;%LLVM_CONFIG%;%PATH%"
  APPVEYOR_SAVE_CACHE_ON_ERROR: true
  matrix:
    - PYTHON: "C:\\Python35"
      PYTHON_VERSION: "3.5"
      PYTHON_ARCH: "64"
      DISTRIBUTIONS: "sdist bdist_wheel"

    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6"
      PYTHON_ARCH: "64"
      DISTRIBUTIONS: "sdist bdist_wheel"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - choco install mingw
#  - choco install llvm
  - choco install make
  - refreshenv
  - "%PYTHON%/Scripts/pip.exe install setuptools"
  - "%PYTHON%/Scripts/pip.exe install python-dateutil"
  - "%PYTHON%/Scripts/pip.exe install numpy"
  - "%PYTHON%/Scripts/pip.exe install colorama"
  - "%PYTHON%/Scripts/pip.exe install typesentry"
  - "%PYTHON%/Scripts/pip.exe install blessed"
  - "%PYTHON%/Scripts/pip.exe install llvmlite"
  - "%PYTHON%/Scripts/pip.exe install pandas"
  - "%PYTHON%/Scripts/pip.exe install pytest"
  - "%PYTHON%/Scripts/pip.exe install virtualenv"
  - "%PYTHON%/Scripts/pip.exe install wheel"

cache:
  - C:\ProgramData\chocolatey\bin -> appveyor.yml
  - C:\ProgramData\chocolatey\lib -> appveyor.yml
  - '%LOCALAPPDATA%\pip\Cache'

test_script:
  - "%PYTHON%/Scripts/pip.exe install .[testing] --no-cache-dir"
  - make

artifacts:
  - path: dist\*
